/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.fullexample.jooq;


import com.steeplesoft.fullexample.jooq.tables.Authors;
import com.steeplesoft.fullexample.jooq.tables.Books;
import com.steeplesoft.fullexample.jooq.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.authors</code>.
     */
    public static final Authors AUTHORS = Authors.AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
